#!/bin/bash

mkdir -p "$SCAN_DIR"


sys_configuration() {
    report_file="$SCAN_DIR/system_configuration_report_$(date +%F_%T).txt"
    (
        echo "System Configuration Report"
        echo "==========================="
        echo "Generated by CPScript's Sytem audit - https://github.com/CPScript/system-audit"
        echo ""
        echo ""
        echo "System Information:"
        echo "------------------"
        echo "$(uname -a)"
        echo "$(cat /etc/os-release)"

        echo ""
        echo "Hardware Information:"
        echo "-------------------"
        echo "$(lshw -short)"

        echo ""
        echo "CPU Information:"
        echo "--------------"
        echo "$(lscpu)"

        echo ""
        echo "Memory Information:"
        echo "-----------------"
        echo "$(free -h)"

        echo ""
        echo "Disk Information:"
        echo "--------------"
        echo "$(df -h)"

        echo ""
        echo "Network Information:"
        echo "------------------"
        echo "$(ip addr show)"
        echo "$(ip route show)"

        echo ""
        echo "Package Information:"
        echo "------------------"
        echo "$(dpkg -l)"

        echo ""
        echo "Services Information:"
        echo "-------------------"
        echo "$(systemctl list-units --type=service)"
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] System configuration report generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file"
}

sys_preformance() {
    report_file="$SCAN_DIR/system_performance_audit_$(date +%F_%T).txt"
    (
        echo "System Performance Audit"
        echo "========================="

        # CPU Usage
        echo "CPU Usage:"
        echo "----------"
        echo "$(mpstat 1 1)"

        # Memory Usage
        echo "Memory Usage:"
        echo "------------"
        echo "$(free -h)"

        # Disk Usage
        echo "Disk Usage:"
        echo "----------"
        echo "$(df -h)"

        # Disk I/O
        echo "Disk I/O:"
        echo "--------"
        echo "$(iostat -dx 1 1)"

        # Network Usage
        echo "Network Usage:"
        echo "-------------"
        echo "$(sar -n DEV 1 1)"

        # Top Processes
        echo "Top Processes:"
        echo "-------------"
        echo "$(top -b -n 1)"

        # System Load
        echo "System Load:"
        echo "------------"
        echo "$(uptime)"

        # Swap Usage
        echo "Swap Usage:"
        echo "----------"
        echo "$(swapon -s)"

        # File System Usage
        echo "File System Usage:"
        echo "-----------------"
        echo "$(df -i)"

        # Inode Usage
        echo "Inode Usage:"
        echo "------------"
        echo "$(df -i)"
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] System performance audit generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file"
}

sys_security() {
    clear
    echo "hello world!"
    sleep 10
}

sys_backup() {
    clear
    echo "hello world!"
    sleep 10
}

sys_restore() {
    clear
    echo "hello world!"
    sleep 10
}

sys_update() {
    clear
    echo "hello world!"
    sleep 10
}
