#!/bin/bash

mkdir -p "$SCAN_DIR"


sys_configuration() {
    report_file="$SCAN_DIR/system_configuration_report_$(date +%F_%T).txt"
    (
        echo "System CONFIGURATION Report"
        echo "==========================="
        echo "Generated by CPScript's System audit - https://github.com/CPScript/system-audit"
        echo ""
        echo ""
        echo "System Information:"
        echo "------------------"
        echo "$(uname -a)"
        echo "$(cat /etc/os-release)"

        echo ""
        echo "Hardware Information:"
        echo "-------------------"
        echo "$(lshw -short)"

        echo ""
        echo "CPU Information:"
        echo "--------------"
        echo "$(lscpu)"

        echo ""
        echo "Memory Information:"
        echo "-----------------"
        echo "$(free -h)"

        echo ""
        echo "Disk Information:"
        echo "--------------"
        echo "$(df -h)"

        echo ""
        echo "Network Information:"
        echo "------------------"
        echo "$(ip addr show)"
        echo "$(ip route show)"

        echo ""
        echo "Package Information:"
        echo "------------------"
        echo "$(dpkg -l)"

        echo ""
        echo "Services Information:"
        echo "-------------------"
        echo "$(systemctl list-units --type=service)"
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] System configuration report generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file"
}

sys_preformance() {
    report_file="$SCAN_DIR/system_performance_audit_$(date +%F_%T).txt"
    (
        echo "System PREFORMANCE Report"
        echo "==========================="
        echo "Generated by CPScript's System audit - https://github.com/CPScript/system-audit"
        echo ""
        echo ""
        echo "System Performance Audit"
        echo "========================="

        echo "CPU Usage:"
        echo "----------"
        echo "$(mpstat 1 1)"

        echo "Memory Usage:"
        echo "------------"
        echo "$(free -h)"

        echo "Disk Usage:"
        echo "----------"
        echo "$(df -h)"

        echo "Disk I/O:"
        echo "--------"
        echo "$(iostat -dx 1 1)"

        echo "Network Usage:"
        echo "-------------"
        echo "$(sar -n DEV 1 1)"

        echo "Top Processes:"
        echo "-------------"
        echo "$(top -b -n 1)"

        echo "System Load:"
        echo "------------"
        echo "$(uptime)"

        echo "Swap Usage:"
        echo "----------"
        echo "$(swapon -s)"

        echo "File System Usage:"
        echo "-----------------"
        echo "$(df -i)"

        echo "Inode Usage:"
        echo "------------"
        echo "$(df -i)"
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] System performance audit generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file"
}

sys_security() {
    report_file="$SCAN_DIR/system_security_audit_$(date +%F_%T).txt"
    (
        echo "System SECURITY Report"
        echo "==========================="
        echo "Generated by CPScript's System audit - https://github.com/CPScript/system-audit"
        echo ""
        echo ""
        echo "System Security Audit"
        echo "====================="

        echo "User Accounts:"
        echo "-------------"
        echo "$(getent passwd)"

        echo "Group Accounts:"
        echo "--------------"
        echo "$(getent group)"

        echo "Sudoers:"
        echo "--------"
        echo "$(sudo cat /etc/sudoers)"

        echo "SSH Configuration:"
        echo "-----------------"
        echo "$(cat /etc/ssh/sshd_config)"

        echo "Firewall Configuration:"
        echo "---------------------"
        echo "$(ufw status)"

        echo "Package Updates:"
        echo "----------------"
        echo "$(apt update && apt list --upgradable)"

        echo "Vulnerable Packages:"
        echo "-------------------"
        echo "$(apt-get install -s --only-upgrade)"

        echo "System Logs:"
        echo "------------"
        echo "$(ls -l /var/log)"

        echo "Login History:"
        echo "--------------"
        echo "$(last)"

        echo "Failed Logins:"
        echo "--------------"
        echo "$(lastb)"

        echo "System Services:"
        echo "----------------"
        echo "$(systemctl list-units --type=service)"

        echo "Open Ports:"
        echo "-----------"
        echo "$(netstat -tlnp)"
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] System security audit generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file"
}

create_backup() {
    echo ""
    echo "Creating a new backup..."
    sleep 5
    local backup_file="$SCAN_DIR/$(date +%F_%T)_backup.tar.gz"
    tar -czf "$backup_file" /etc /var/log /home /root
    echo ""
    echo "Backup created: $backup_file please wait"
    sleep 5
    local report_file="$SCAN_DIR/backup_audit_$(date +%F_%T).txt"
    (
        echo "system BACKUP audit"
        echo "==================="
        echo "Generated by CPScript's System audit - https://github.com/CPScript/system-audit"
        echo ""
        echo ""
        echo "Backup file: $backup_file"
        echo "Backup size: $(du -h $backup_file)"
        echo "Backup contents:"
        tar -tf "$backup_file"
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Backup audit report generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file"
}

sys_backup() { 
    sleep 3
    if [ "$(id -u)" != "0" ]; then
        echo "Error: This script must be run as root."
        exit 1
    fi   

    # Check if a backup exists
    if [ -d "$SCAN_DIR" ]; then
        echo "Audit directory found: $SCAN_DIR"
        echo "Checking for existing backups..."
        if [ "$(ls -A $SCAN_DIR)" ]; then
            echo "Existing backup found: $(ls -A $SCAN_DIR)"
        else
            echo "No existing backup found. Creating a new backup..."
            create_backup
        fi
    else
        echo "Audit directory not found. Creating a new backup..."
        create_backup
    fi
}

sys_restore(){

    if [ "$(id -u)" != "0" ]; then
        echo "Error: This script must be run as root."
        exit 1
    fi

    echo "System RESTORATION Audit"
    echo "======================="

    echo "Checking for faulty system files..."
    if [ "$(find / -type f -size +100M)" ]; then
        echo "Faulty system files found:"
        find / -type f -size +100M
    else
        echo "No faulty system files found."
    fi

    echo "Checking for corrupted system packages..."
    if [ "$(dpkg --verify)" ]; then
        echo "Corrupted system packages found:"
        dpkg --verify
    else
        echo "No corrupted system packages found."
    fi

    echo "Checking for system configuration errors..."
    if [ "$(find /etc -type f -size 0)" ]; then
        echo "System configuration errors found:"
        find /etc -type f -size 0
    else
        echo "No system configuration errors found."
    fi

    echo "Checking for system log errors..."
    if [ "$(find /var/log -type f -size +100M)" ]; then
        echo "System log errors found:"
        find /var/log -type f -size +100M
    else
        echo "No system log errors found."
    fi

    echo "Checking for system service errors..."
    if [ "$(systemctl list-units --state=failed)" ]; then
        echo "System service errors found:"
        systemctl list-units --state=failed
    else
        echo "No system service errors found."
    fi

    local report_file="$REPORT_DIR/system_restoration_audit_$(date +%F_%T).txt"
    (
        echo "System RESTORATION Audit"
        echo "==========================="
        echo "Generated by CPScript's System audit - https://github.com/CPScript/system-audit"
        echo ""
        echo ""
        echo "Faulty system files:"
        find / -type f -size +100M
        echo "Corrupted system packages:"
        dpkg --verify
        echo "System configuration errors:"
        find /etc -type f -size 0
        echo "System log errors:"
        find /var/log -type f -size +100M
        echo "System service errors:"
        systemctl list-units --state=failed
    ) | tee -a "$report_file"

    echo "[$(date +'%Y-%m-%d %H:%M:%S')] System restoration audit report generated successfully!"
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] Report file: $report_file" 
}
    sys_update() {
        clear
        echo "hello world!" 
        sleep 10
    }
